# Generated by Django 3.0.7 on 2020-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='question_number',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
