# Generated by Django 3.0.7 on 2020-11-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0003_auto_20200826_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_key',
            new_name='team_urlslug',
        ),
    ]
