# Generated by Django 3.0.7 on 2020-11-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0004_auto_20201113_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='team',
        ),
    ]
