# Generated by Django 3.0.7 on 2020-11-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0005_auto_20201114_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preset_question',
            field=models.BooleanField(default=True),
        ),
    ]
