# Generated by Django 3.0.7 on 2020-11-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0006_entry_preset_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='preset_question',
            new_name='is_preset_question',
        ),
    ]
