# Generated by Django 3.0.7 on 2020-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0007_auto_20201115_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_preset_question',
            field=models.BooleanField(default=False),
        ),
    ]
