# Generated by Django 3.0.7 on 2020-11-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offsite_questions', '0008_auto_20201115_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offsite_questions.Entry')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offsite_questions.Team')),
            ],
        ),
    ]
